[package]
name = "sysdoc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { workspace = true }
pulldown-cmark = { workspace = true }
walkdir = { workspace = true }
csv = { workspace = true }
